services:
  web:
    build: .
    image: ${DOCKER_USER}/counter-app:1.0
    environment:
      - REDIS_HOST=db-service
    ports:
      - "${WEB_PORT}:5000"
    depends_on:
      - db-service
    networks:
      - app-network

  db-service:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  redis-data:
